# Generated by Django 3.0 on 2020-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0003_auto_20200207_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edition', models.PositiveIntegerField()),
                ('publication_year', models.PositiveIntegerField()),
                ('authors', models.ManyToManyField(to='authors.Author')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ['-publication_year', 'name'],
            },
        ),
    ]
