version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authors
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  # migrate:
  #   # restart: on-failure
  #   image: work-at-olist_authors
  #   working_dir: /work-at-olist/src
  #   command: python src/manage.py migrate --noinput --settings=settings.dev
  #   volumes:
  #     - .:/work-at-olist
  #   env_file: config/api.env
  #   depends_on:
  #     - db

  # tests:
  #   image: test_authors
  #   command: python -m unittest discover -s src -v
  #   # command: sh -c "coverage run --omit="**migrations**,**tests**" -m unittest discover -s src -v && coverage report"
  #   volumes:
  #     - .:/work-at-olist
  #   env_file: config/api.env
  #   depends_on:
  #     - db
    

  authors:
    build: .
    restart: on-failure
    command: python src/manage.py runserver 0.0.0.0:8000 --settings=settings.dev
    volumes:
      - .:/work-at-olist
    ports:
      - "8000:8000"
    env_file: config/api.env
    depends_on:
      - db
      # - migrate
    #   - tests
