version: '3'

services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authors
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  authors:
    build: .
    restart: on-failure
    command: python src/manage.py runserver 0.0.0.0:8000 --settings=settings.dev
    volumes:
      - .:/work-at-olist
    ports:
      - "8000:8000"
    env_file: config/api.env
    depends_on:
      - db
